

var KeyWords = {
    AS : "as",
    CASE : "case",
    CATCH : "catch",
    CLASS : "class",
    CONST : "const",
    DEFAULT : "default",
    DELETE : "delete",
    DO : "do",
    DYNAMIC : "dynamic",
    EACH : "each",
    ELSE : "else",
    EOF : "__END__",
    EXTENDS : "extends",
    FINAL : "final",
    FINALLY : "finally",
    FOR : "for",
    FUNCTION : "function",
    GET : "get",
    IF : "if",
    IMPLEMENTS : "implements",
    IMPORT : "import",
    IN : "in",
    INCLUDE : "include",
    INCLUDE_AS2 : "#include",
    INSTANCE_OF : "instanceof",
    INTERFACE : "interface",
    INTERNAL : "internal",
    INTRINSIC : "intrinsic",
    IS : "is",
    NAMESPACE : "namespace",
    NEW : "new",
    OVERRIDE : "override",
    PACKAGE : "package",
    PRIVATE : "private",
    PROTECTED : "protected",
    PUBLIC : "public",
    RETURN : "return",
    SET : "set",
    STATIC : "static",
    SUPER : "super",
    SWITCH : "switch",
    TRY : "try",
    TYPEOF : "typeof",
    USE : "use",
    VAR : "var",
    VOID : "void",
    WHILE : "while",

    TRUE: 'true',
    FALSE: 'false',
    NULL: 'null',
    UNDEFINED: 'undefined',
    NaN: 'NaN'
    
};

export = KeyWords;